// lib/calculatorNames.ts
// Auto-generated mapping of calculator slug → title
// Last updated: 2026-06-05

export const calculatorDescriptiveNames: Record<string, string> = {
  "sip-calculator": "SIP Calculator",
  "step-up-sip-calculator": "Step-Up SIP Calculator",
  "top-up-sip-calculator": "Top-Up SIP Calculator",
  "perpetual-sip-calculator": "Perpetual SIP Calculator",
  "lumpsum-calculator": "Lumpsum Calculator",
  "swp-calculator": "SWP Calculator",
  "swp-inflation-calculator": "SWP Inflation Calculator",
  "swp-tax-calculator": "SWP Tax Calculator",
  "stp-calculator": "STP Calculator",
  "value-averaging-calculator": "Value Averaging Calculator",
  "xirr-calculator": "XIRR Calculator",
  "cagr-calculator": "CAGR Calculator",
  "mf-overlap-2-calculator": "Mutual Fund Overlap (2 Funds)",
  "mf-overlap-3-calculator": "Mutual Fund Overlap (3+ Funds)",
  "direct-vs-regular-calculator": "Direct vs Regular Calculator",
  "elss-tax-calculator": "ELSS Tax Calculator",
  "nps-calculator": "NPS Calculator",
  "nps-partial-withdrawal-calculator": "NPS Partial Withdrawal Calculator",
  "epf-calculator": "EPF Calculator",
  "ppf-calculator": "PPF Calculator",
  "brokerage-zerodha-calculator": "Zerodha Brokerage Calculator",
  "brokerage-groww-calculator": "Groww Brokerage Calculator",
  "brokerage-angel-calculator": "Angel One Brokerage Calculator",
  "intraday-profit-calculator": "Intraday Profit/Loss Calculator",
  "fo-brokerage-calculator": "F&O Brokerage Calculator",
  "futures-margin-calculator": "Futures Margin Calculator",
  "option-margin-calculator": "Option Margin Calculator",
  "option-greeks-calculator": "Option Greeks Calculator",
  "stock-average-calculator": "Stock Average Price Calculator",
  "stock-split-calculator": "Stock Split/Bonus Calculator",
  "rights-issue-calculator": "Rights Issue Calculator",
  "stock-sip-calculator": "Stock SIP Calculator",
  "ltcg-tax-shares-calculator": "LTCG Tax on Shares Calculator",
  "stcg-tax-shares-calculator": "STCG Tax on Shares Calculator",
  "stock-beta-calculator": "Stock Beta Calculator",
  "income-tax-old-calculator": "Old Regime Income Tax Calculator",
  "income-tax-new-calculator": "New Regime Income Tax Calculator",
  "hra-exemption-calculator": "HRA Exemption Calculator",
  "section-80c-optimizer": "Section 80C Optimizer",
  "section-80d-calculator": "Section 80D Calculator",
  "nri-tax-calculator": "NRI Tax Calculator",
  "tds-fd-calculator": "TDS on FD/RD Calculator",
  "capital-gains-property-calculator": "Capital Gains on Property Calculator",
  "capital-gains-debt-fund-calculator": "Capital Gains on Debt Funds",
  "gst-calculator": "GST Calculator",
  "freelancer-tax-calculator": "Freelancer Tax (44ADA) Calculator",
  "advance-tax-calculator": "Advance Tax Calculator",
  "esop-tax-calculator": "ESOP Tax Calculator",
  "salary-arrears-relief-calculator": "Salary Arrears Relief Calculator",
  "retirement-corpus-calculator": "Retirement Corpus Calculator",
  "fire-number-calculator": "FIRE Number Calculator",
  "apy-calculator": "Atal Pension Yojana (APY) Calculator",
  "scss-calculator": "Senior Citizen SCSS Calculator",
  "pmvvy-calculator": "PMVVY Calculator",
  "pomis-calculator": "Post Office MIS Calculator",
  "sgb-calculator": "Sovereign Gold Bond Calculator",
  "ssy-calculator": "Sukanya Samriddhi Yojana Calculator",
  "nsc-calculator": "National Savings Certificate Calculator",
  "kvp-calculator": "Kisan Vikas Patra Calculator",
  "home-loan-emi-calculator": "Home Loan EMI Calculator",
  "home-loan-prepayment-calculator": "Home Loan Prepayment Calculator",
  "home-loan-balance-transfer-calculator": "Home Loan Balance Transfer Calculator",
  "car-loan-emi-calculator": "Car Loan EMI Calculator",
  "personal-loan-emi-calculator": "Personal Loan EMI Calculator",
  "gold-loan-emi-calculator": "Gold Loan EMI Calculator",
  "education-loan-calculator": "Education Loan Calculator",
  "lap-calculator": "Loan Against Property Calculator",
  "mudra-loan-calculator": "Mudra Loan Calculator",
  "credit-card-payoff-calculator": "Credit Card Payoff Calculator",
  "nre-fd-vs-nro-fd-calculator": "NRE FD vs NRO FD Calculator",
  "nri-repatriation-calculator": "NRI Repatriation Calculator",
  "rnor-status-calculator": "RNOR Status Calculator",
  "crypto-tax-calculator": "Crypto Tax Calculator",
  "ipo-gmp-calculator": "IPO GMP Calculator",
  "ipo-allotment-simulator": "IPO Allotment Simulator",
  "gold-etf-vs-physical-calculator": "Gold ETF vs Physical Gold Calculator",
  "real-estate-vs-mf-calculator": "Real Estate vs MF Calculator",
  "ev-vs-petrol-calculator": "EV vs Petrol Cost Calculator",
  "solar-breakeven-calculator": "Solar Break‑even Calculator",
  "sip-vs-lumpsum": "SIP vs Lumpsum Comparator",
  "stepup-vs-normal-sip": "Step‑Up SIP vs Normal SIP",
  "swp-vs-monthly-fd": "SWP vs Monthly FD",
  "swp-vs-dividend-reinvestment": "SWP vs Dividend Reinvestment",
  "direct-vs-regular-mf": "Direct vs Regular Mutual Fund",
  "elss-vs-ppf": "ELSS vs PPF",
  "elss-vs-nps": "ELSS vs NPS",
  "elss-vs-ppf-vs-nps": "ELSS vs PPF vs NPS",
  "large-cap-vs-mid-cap-sip": "Large Cap vs Mid Cap SIP",
  "active-vs-index-fund": "Active vs Index Fund",
  "growth-vs-idcw": "Growth vs IDCW",
  "value-averaging-vs-sip": "Value Averaging vs SIP",
  "liquid-fund-vs-savings-account": "Liquid Fund vs Savings Account",
  "arbitrage-vs-liquid-fund": "Arbitrage vs Liquid Fund",
  "sgb-vs-gold-etf": "SGB vs Gold ETF",
  "nps-vs-ppf": "NPS vs PPF",
  "nps-vs-epf-vs-ppf": "NPS vs EPF vs PPF",
  "mf-vs-ulip": "Mutual Fund vs ULIP",
  "mf-vs-real-estate": "Mutual Fund vs Real Estate",
  "mf-vs-gold": "Mutual Fund vs Gold",
  "child-goal-sip-vs-lumpsum": "Child Goal SIP vs Lumpsum",
  "retirement-swp-vs-annuity": "Retirement SWP vs Annuity",
  "scss-vs-pmvvy": "SCSS vs PMVVY",
  "scss-vs-fd": "SCSS vs FD",
  "pomis-vs-scss": "POMIS vs SCSS",
  "senior-fd-vs-nre-fd": "Senior FD vs NRE FD",
  "nps-vs-apy": "NPS vs APY",
  "fire-4percent-vs-3percent": "FIRE 4% Rule vs 3% Rule",
  "fire-equity-vs-balanced": "FIRE Equity vs Balanced",
  "ppf-vs-ssy": "PPF vs SSY",
  "nsc-vs-kvp": "NSC vs KVP",
  "sgb-vs-gold-fd-senior": "SGB vs Gold FD Senior",
  "monthly-pension-apy-vs-pmvvy": "Monthly Pension APY vs PMVVY",
  "post-office-mis-vs-rd": "Post Office MIS vs RD",
  "nps-annuity-vs-swp": "NPS Annuity vs SWP",
  "reverse-mortgage-vs-home-sale": "Reverse Mortgage vs Home Sale",
  "fd-vs-rd": "FD vs RD",
  "cumulative-vs-non-cumulative-fd": "Cumulative vs Non‑Cumulative FD",
  "tax-saver-fd-vs-normal-fd": "Tax‑Saver FD vs Normal FD",
  "corporate-fd-vs-bank-fd": "Corporate FD vs Bank FD",
  "sweep-in-vs-normal-fd": "Sweep‑in FD vs Normal FD",
  "ppf-vs-fd-post-tax": "PPF vs FD Post‑Tax",
  "nre-vs-nro": "NRE vs NRO",
  "nre-vs-fcnr": "NRE vs FCNR",
  "nro-fd-vs-resident-fd": "NRO FD vs Resident FD",
  "nri-home-loan-vs-resident-home-loan": "NRI Home Loan vs Resident Loan",
  "dtaa-vs-no-dtaa": "DTAA vs No DTAA",
  "rent-vs-buy": "Rent vs Buy",
  "rent-vs-pg-vs-own": "Rent vs PG vs Own House",
  "under-construction-vs-ready-to-move": "Under‑Construction vs Ready‑to‑Move",
  "property-vs-mf": "Property vs Mutual Fund",
  "direct-property-vs-reit": "Direct Property vs REIT",
  "residential-vs-commercial": "Residential vs Commercial Property",
  "new-property-vs-resale": "New Property vs Resale",
  "joint-ownership-vs-single": "Joint Ownership vs Single",
  "pmay-vs-non-pmay": "PMAY vs Non‑PMAY",
  "home-loan-vs-rent-invest": "Home Loan vs Rent + Invest",
  "standard-deduction-vs-actual": "Standard Deduction vs Actual",
  "tds-rent-194i-vs-194ib": "TDS on Rent 194I vs 194IB",
  "54-vs-54f": "Section 54 vs 54F",
  "indexation-vs-non-indexation": "Indexation vs Non‑Indexation",
  "term-vs-ulip": "Term vs ULIP",
  "term-vs-endowment": "Term vs Endowment",
  "term-vs-savings-plan": "Term vs Savings Plan",
  "term-invest-vs-term-only": "Term + Invest vs Term Only",
  "health-individual-vs-family-floater": "Individual vs Family Floater Health",
  "senior-vs-regular-health": "Senior vs Regular Health Insurance",
  "health-ncb-vs-no-ncb": "Health NCB vs No NCB",
  "car-comprehensive-vs-third-party": "Comprehensive vs Third‑Party Car Insurance",
  "car-zero-dep-vs-normal": "Zero Dep vs Normal Car Insurance",
  "bike-od-vs-liability": "Bike Own Damage vs Liability Only",
  "lic-jeevan-labah-vs-term-ppf": "LIC Jeevan Labh vs Term + PPF",
  "pmjjby-vs-private-term": "PMJJBY vs Private Term Insurance",
  "health-portability-vs-new": "Health Portability vs New Policy",
  "critical-illness-rider-vs-separate": "CI Rider vs Separate Plan",
  "ev-vs-petrol-5y": "EV vs Petrol (5 Year)",
  "solar-vs-grid": "Solar vs Grid Electricity",
  "broadband-vs-5g": "Broadband vs 5G Hotspot",
  "prepaid-vs-postpaid": "Prepaid vs Postpaid Mobile",
  "ott-pack-vs-individual": "OTT Pack vs Individual Subscriptions",
  "cloud-storage-vs-external-hdd": "Cloud Storage vs External HDD",
  "lpg-vs-induction": "LPG vs Induction Cooking",
  "own-vehicle-vs-public": "Own Vehicle vs Public Transport",
  "wedding-loan-vs-savings": "Wedding Loan vs Savings",
  "credit-card-rewards-vs-annual-fee": "Credit Card Rewards vs Annual Fee",
  "cashback-vs-points": "Cashback vs Points",
  "personal-loan-vs-credit-card-emi": "Personal Loan vs Credit Card EMI",
  "loan-vs-pf-withdrawal": "Loan vs PF Withdrawal",
  "sip-vs-rd": "SIP vs RD",
  "nfo-vs-existing-fund": "NFO vs Existing Fund",
  "monthly-sip-return-calculator": "Monthly SIP Return Calculator",
  "mutual-fund-returns-calculator": "Mutual Fund Returns Calculator",
  "goal-based-sip-calculator": "Goal‑Based SIP Calculator",
  "mutual-fund-xirr-returns": "Mutual Fund XIRR Returns",
  "elss-tax-saving-calculator": "ELSS Tax Saving Calculator",
  "systematic-withdrawal-plan-calculator": "Systematic Withdrawal Plan Calculator",
  "systematic-transfer-plan-calculator": "Systematic Transfer Plan Calculator",
  "bike-loan-emi-calculator": "Bike Loan EMI Calculator",
  "education-loan-emi-calculator": "Education Loan EMI Calculator",
  "loan-eligibility-calculator": "Loan Eligibility Calculator",
  "loan-tenure-calculator": "Loan Tenure Calculator",
  "loan-prepayment-calculator": "Loan Prepayment Calculator",
  "balance-transfer-calculator": "Balance Transfer Calculator",
  "compound-interest-calculator": "Compound Interest Calculator",
  "roi-calculator": "ROI Calculator",
  "fd-calculator": "Fixed Deposit Calculator",
  "rd-calculator": "Recurring Deposit Calculator",
  "annuity-calculator": "Annuity Calculator",
  "inflation-calculator": "Inflation Calculator",
  "brokerage-calculator": "Brokerage Calculator",
  "margin-calculator": "Margin Calculator",
  "average-price-calculator": "Average Price Calculator",
  "dividend-yield-calculator": "Dividend Yield Calculator",
  "stock-cagr-calculator": "Stock CAGR Calculator",
  "target-price-calculator": "Target Price Calculator",
  "risk-management-calculator": "Risk Management Calculator",
  "p-e-ratio-calculator": "P/E Ratio Calculator",
  "p-b-ratio-calculator": "P/B Ratio Calculator",
  "term-insurance-calculator": "Term Insurance Calculator",
  "health-insurance-calculator": "Health Insurance Calculator",
  "life-insurance-cover-calculator": "Life Insurance Cover Calculator",
  "simple-interest-calculator": "Simple Interest Calculator",
  "risk-reward-ratio-calculator": "Risk‑Reward Ratio Calculator",
  "stop-loss-target-calculator": "Stop Loss / Target Calculator",
  "trailing-stop-loss-calculator": "Trailing Stop Loss Calculator",
  "stock-risk-calculator": "Stock Risk Calculator",
  "volatility-calculator": "Volatility Calculator",
  "max-drawdown-calculator": "Max Drawdown Calculator",
  "portfolio-allocation-calculator": "Portfolio Allocation Calculator",
  "portfolio-rebalancing-calculator": "Portfolio Rebalancing Calculator",
  "bull-call-spread-calculator": "Bull Call Spread Calculator",
  "bear-put-spread-calculator": "Bear Put Spread Calculator",
  "implied-volatility-calculator": "Implied Volatility Calculator",
  "options-greeks-calculator": "Options Greeks Calculator",
  "lap-emi-calculator": "Loan Against Property EMI Calculator",
  "top-up-loan-eligibility-calculator": "Top‑Up Loan Eligibility Calculator",
  "reducing-interest-rate-emi-calculator": "Reducing Interest EMI Calculator",
  "flat-interest-rate-emi-calculator": "Flat Interest EMI Calculator",
  "loan-processing-fee-calculator": "Loan Processing Fee Calculator",
  "overdraft-interest-calculator": "Overdraft Interest Calculator",
  "business-loan-emi-calculator": "Business Loan EMI Calculator",
  "mudra-loan-emi-calculator": "Mudra Loan EMI Calculator",
  "kisan-credit-card-loan-calculator": "Kisan Credit Card Loan Calculator",
  "used-car-loan-emi-calculator": "Used Car Loan EMI Calculator",
  "used-bike-loan-emi-calculator": "Used Bike Loan EMI Calculator",
  "commercial-vehicle-loan-emi-calculator": "Commercial Vehicle Loan EMI Calculator",
  "electric-vehicle-loan-emi-calculator": "Electric Vehicle Loan EMI Calculator",
  "foreclosure-loan-calculator": "Foreclosure Loan Calculator",
  "penal-interest-emi-calculator": "Penal Interest EMI Calculator",
  "overdue-interest-emi-calculator": "Overdue Interest EMI Calculator",
  "sip-irr-calculator": "SIP IRR Calculator",
  "lumpsum-irr-calculator": "Lumpsum IRR Calculator",
  "insurance-irr-calculator": "Insurance IRR Calculator",
  "calculator": "Generic Financial Calculator",
  "beta-calculator": "Beta Calculator",
  "position-size-calculator": "Position Size Calculator",
  "options-breakeven-calculator": "Options Breakeven Calculator",
  "iron-condor-calculator": "Iron Condor Calculator"
};

export function getDescriptiveName(slug: string): string {
  return calculatorDescriptiveNames[slug] || slug.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}
